### ISSUE TITLE
TwigCompiler

### ISSUE THREAD

**Issue by darkalchemy** [odan/twig-translation#5]
When I import and use your TwigCompiler, this line `$this->cachePath = str_replace('\\', '/', trim($cachePath, '\/'));`
removes leading '/', I'm assuming to make the ensure a relative path. But my path is an absolute path and this breaks the ability to create the dir, if needed.

When I used this in my project, before you updated this, I had to remove the str_replace and simply use `$this->cachePath = trim($cachePath);`

When I look at your [Slim4-Skeleton](https://github.com/odan/slim4-skeleton/blob/master/config/defaults.php#L56) it appears that you are also using an absolute path, so I am not sure how it works there, either.

I am probably missing something that you have configured in your project that I do not have in mine.

Any help would be appreciated.

Thanks again for the quick update.

I suppose that a right trim would do the trick also .

**Comment by odan** [comment]
This line is intended to ensure that Windows paths do not contain `\` in the path.
The trim is problematic in some cases. This will be fixed.

**Comment by odan** [comment]
Please update to the latest version an try it again. Tell me if it works for you.

**Comment by darkalchemy** [comment]
The fix appears to be returning the parent directory name since we are giving it a directory and not a file.
If I add a '/*' to the cachePath it returns the correct path.

I think that ```str_replace('\\', '/', $cachePath);``` is all you need.

**Comment by odan** [comment]
It should be fixed now.

**Comment by darkalchemy** [comment]
Thanks for this. :)
