### ISSUE TITLE
Im stuck ... ConfigCacheFactory' not found

### ISSUE THREAD

**Issue by ledahu** [odan/twig-translation#9]
Hi Odan, 

any idea on this ? 

`
Type: Error
Code: 0
Message: Class 'Symfony\Component\Config\ConfigCacheFactory' not found
File: ...\vendor\symfony\translation\Translator.php
Line: 461
Trace

#0 ..\vendor\symfony\translation\Translator.php(287): Symfony\Component\Translation\Translator->getConfigCacheFactory()
#1 ..\vendor\symfony\translation\Translator.php(261): Symfony\Component\Translation\Translator->initializeCacheCatalogue('fr_FR')
#2 ..\vendor\symfony\translation\Translator.php(240): Symfony\Component\Translation\Translator->loadCatalogue('fr_FR')
#3 ..\vendor\symfony\translation\Translator.php(206): Symfony\Component\Translation\Translator->getCatalogue('fr_FR')
#4 ..\vendor\odan\twig-translation\src\TwigTranslationExtension.php(66): Symfony\Component\Translation\Translator->trans('Welcome', Array)
#5 ..\tmp\twig\fd\fd9eef701efe2a41a295486cca34e1a74fd5a02c9924a43be694b595671751e5.php(51): Odan\Twig\TwigTranslationExtension->__('Welcome')`

**Comment by odan** [comment]
This sounds like an composer autoloader issue. 
Have you tried to run: `composer dump-autoload` ?

**Comment by ledahu** [comment]
no effect 

i had to add `composer require symfony/config`

and now, no more errors but no traduction (i m using symfony/twig-bridge now, as you recommend it)

cache file are created , but nothing ... if you have an idea, you are welcome !

in the fr_FR_messages.mo Only 'Welcome' traduced to "Bonjour" 

`        var_dump($this->translator);
        var_dump($this->translator->trans('Welcome'));`

here is a translator dump 

object(Symfony\Component\Translation\Translator)#108 (12) {
  ["catalogues":protected]=>
  array(0) {
  }
  ["locale":"Symfony\Component\Translation\Translator":private]=>
  string(5) "fr_FR"
  ["fallbackLocales":"Symfony\Component\Translation\Translator":private]=>
  array(0) {
  }
  ["loaders":"Symfony\Component\Translation\Translator":private]=>
  array(1) {
    ["mo"]=>
    object(Symfony\Component\Translation\Loader\MoFileLoader)#111 (0) {
    }
  }
  ["resources":"Symfony\Component\Translation\Translator":private]=>
  array(1) {
    ["fr_FR"]=>
    array(1) {
      [0]=>
      array(3) {
        [0]=>
        string(2) "mo"
        [1]=>
        string(64) "C:\wamp64\www\TinyStamp/resources/translations/fr_FR_messages.mo"
        [2]=>
        string(8) "messages"
      }
    }
  }
  ["formatter":"Symfony\Component\Translation\Translator":private]=>
  object(Symfony\Component\Translation\Formatter\MessageFormatter)#107 (2) {
    ["translator":"Symfony\Component\Translation\Formatter\MessageFormatter":private]=>
    object(Symfony\Component\Translation\IdentityTranslator)#109 (1) {
      ["locale":"Symfony\Component\Translation\IdentityTranslator":private]=>
      NULL
    }
    ["intlFormatter":"Symfony\Component\Translation\Formatter\MessageFormatter":private]=>
    object(Symfony\Component\Translation\Formatter\IntlFormatter)#110 (2) {
      ["hasMessageFormatter":"Symfony\Component\Translation\Formatter\IntlFormatter":private]=>
      NULL
      ["cache":"Symfony\Component\Translation\Formatter\IntlFormatter":private]=>
      array(0) {
      }
    }
  }
  ["cacheDir":"Symfony\Component\Translation\Translator":private]=>
  string(32) "C:\wamp64\www\TinyStamp/tmp/twig"
  ["debug":"Symfony\Component\Translation\Translator":private]=>
  bool(true)
  ["cacheVary":"Symfony\Component\Translation\Translator":private]=>
  array(0) {
  }
  ["configCacheFactory":"Symfony\Component\Translation\Translator":private]=>
  NULL
  ["parentLocales":"Symfony\Component\Translation\Translator":private]=>
  NULL
  ["hasIntlFormatter":"Symfony\Component\Translation\Translator":private]=>
  bool(true)
}

**Comment by ledahu** [comment]
Arfff..... its ok 

$ù^* !!! cache .... :(
